// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

// Protobuf Java Version: 3.25.1
package marketplace.product;

public final class Product {
  private Product() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetProductForCartRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:marketplace.product.GetProductForCartRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 product_id = 1;</code>
     * @return The productId.
     */
    long getProductId();
  }
  /**
   * Protobuf type {@code marketplace.product.GetProductForCartRequest}
   */
  public static final class GetProductForCartRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:marketplace.product.GetProductForCartRequest)
      GetProductForCartRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetProductForCartRequest.newBuilder() to construct.
    private GetProductForCartRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetProductForCartRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetProductForCartRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return marketplace.product.Product.internal_static_marketplace_product_GetProductForCartRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return marketplace.product.Product.internal_static_marketplace_product_GetProductForCartRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              marketplace.product.Product.GetProductForCartRequest.class, marketplace.product.Product.GetProductForCartRequest.Builder.class);
    }

    public static final int PRODUCT_ID_FIELD_NUMBER = 1;
    private long productId_ = 0L;
    /**
     * <code>int64 product_id = 1;</code>
     * @return The productId.
     */
    @java.lang.Override
    public long getProductId() {
      return productId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (productId_ != 0L) {
        output.writeInt64(1, productId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (productId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, productId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof marketplace.product.Product.GetProductForCartRequest)) {
        return super.equals(obj);
      }
      marketplace.product.Product.GetProductForCartRequest other = (marketplace.product.Product.GetProductForCartRequest) obj;

      if (getProductId()
          != other.getProductId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProductId());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static marketplace.product.Product.GetProductForCartRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static marketplace.product.Product.GetProductForCartRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static marketplace.product.Product.GetProductForCartRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static marketplace.product.Product.GetProductForCartRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static marketplace.product.Product.GetProductForCartRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static marketplace.product.Product.GetProductForCartRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static marketplace.product.Product.GetProductForCartRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static marketplace.product.Product.GetProductForCartRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static marketplace.product.Product.GetProductForCartRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static marketplace.product.Product.GetProductForCartRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static marketplace.product.Product.GetProductForCartRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static marketplace.product.Product.GetProductForCartRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(marketplace.product.Product.GetProductForCartRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code marketplace.product.GetProductForCartRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:marketplace.product.GetProductForCartRequest)
        marketplace.product.Product.GetProductForCartRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return marketplace.product.Product.internal_static_marketplace_product_GetProductForCartRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return marketplace.product.Product.internal_static_marketplace_product_GetProductForCartRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                marketplace.product.Product.GetProductForCartRequest.class, marketplace.product.Product.GetProductForCartRequest.Builder.class);
      }

      // Construct using marketplace.product.Product.GetProductForCartRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        productId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return marketplace.product.Product.internal_static_marketplace_product_GetProductForCartRequest_descriptor;
      }

      @java.lang.Override
      public marketplace.product.Product.GetProductForCartRequest getDefaultInstanceForType() {
        return marketplace.product.Product.GetProductForCartRequest.getDefaultInstance();
      }

      @java.lang.Override
      public marketplace.product.Product.GetProductForCartRequest build() {
        marketplace.product.Product.GetProductForCartRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public marketplace.product.Product.GetProductForCartRequest buildPartial() {
        marketplace.product.Product.GetProductForCartRequest result = new marketplace.product.Product.GetProductForCartRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(marketplace.product.Product.GetProductForCartRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.productId_ = productId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof marketplace.product.Product.GetProductForCartRequest) {
          return mergeFrom((marketplace.product.Product.GetProductForCartRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(marketplace.product.Product.GetProductForCartRequest other) {
        if (other == marketplace.product.Product.GetProductForCartRequest.getDefaultInstance()) return this;
        if (other.getProductId() != 0L) {
          setProductId(other.getProductId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                productId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long productId_ ;
      /**
       * <code>int64 product_id = 1;</code>
       * @return The productId.
       */
      @java.lang.Override
      public long getProductId() {
        return productId_;
      }
      /**
       * <code>int64 product_id = 1;</code>
       * @param value The productId to set.
       * @return This builder for chaining.
       */
      public Builder setProductId(long value) {

        productId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 product_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        productId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:marketplace.product.GetProductForCartRequest)
    }

    // @@protoc_insertion_point(class_scope:marketplace.product.GetProductForCartRequest)
    private static final marketplace.product.Product.GetProductForCartRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new marketplace.product.Product.GetProductForCartRequest();
    }

    public static marketplace.product.Product.GetProductForCartRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetProductForCartRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetProductForCartRequest>() {
      @java.lang.Override
      public GetProductForCartRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetProductForCartRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetProductForCartRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public marketplace.product.Product.GetProductForCartRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetProductForCartResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:marketplace.product.GetProductForCartResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 product_id = 1;</code>
     * @return The productId.
     */
    long getProductId();

    /**
     * <code>string price = 2;</code>
     * @return The price.
     */
    java.lang.String getPrice();
    /**
     * <code>string price = 2;</code>
     * @return The bytes for price.
     */
    com.google.protobuf.ByteString
        getPriceBytes();

    /**
     * <code>bool available = 3;</code>
     * @return The available.
     */
    boolean getAvailable();
  }
  /**
   * Protobuf type {@code marketplace.product.GetProductForCartResponse}
   */
  public static final class GetProductForCartResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:marketplace.product.GetProductForCartResponse)
      GetProductForCartResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetProductForCartResponse.newBuilder() to construct.
    private GetProductForCartResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetProductForCartResponse() {
      price_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetProductForCartResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return marketplace.product.Product.internal_static_marketplace_product_GetProductForCartResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return marketplace.product.Product.internal_static_marketplace_product_GetProductForCartResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              marketplace.product.Product.GetProductForCartResponse.class, marketplace.product.Product.GetProductForCartResponse.Builder.class);
    }

    public static final int PRODUCT_ID_FIELD_NUMBER = 1;
    private long productId_ = 0L;
    /**
     * <code>int64 product_id = 1;</code>
     * @return The productId.
     */
    @java.lang.Override
    public long getProductId() {
      return productId_;
    }

    public static final int PRICE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object price_ = "";
    /**
     * <code>string price = 2;</code>
     * @return The price.
     */
    @java.lang.Override
    public java.lang.String getPrice() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        price_ = s;
        return s;
      }
    }
    /**
     * <code>string price = 2;</code>
     * @return The bytes for price.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPriceBytes() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVAILABLE_FIELD_NUMBER = 3;
    private boolean available_ = false;
    /**
     * <code>bool available = 3;</code>
     * @return The available.
     */
    @java.lang.Override
    public boolean getAvailable() {
      return available_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (productId_ != 0L) {
        output.writeInt64(1, productId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(price_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, price_);
      }
      if (available_ != false) {
        output.writeBool(3, available_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (productId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, productId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(price_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, price_);
      }
      if (available_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, available_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof marketplace.product.Product.GetProductForCartResponse)) {
        return super.equals(obj);
      }
      marketplace.product.Product.GetProductForCartResponse other = (marketplace.product.Product.GetProductForCartResponse) obj;

      if (getProductId()
          != other.getProductId()) return false;
      if (!getPrice()
          .equals(other.getPrice())) return false;
      if (getAvailable()
          != other.getAvailable()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProductId());
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice().hashCode();
      hash = (37 * hash) + AVAILABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAvailable());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static marketplace.product.Product.GetProductForCartResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static marketplace.product.Product.GetProductForCartResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static marketplace.product.Product.GetProductForCartResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static marketplace.product.Product.GetProductForCartResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static marketplace.product.Product.GetProductForCartResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static marketplace.product.Product.GetProductForCartResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static marketplace.product.Product.GetProductForCartResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static marketplace.product.Product.GetProductForCartResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static marketplace.product.Product.GetProductForCartResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static marketplace.product.Product.GetProductForCartResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static marketplace.product.Product.GetProductForCartResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static marketplace.product.Product.GetProductForCartResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(marketplace.product.Product.GetProductForCartResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code marketplace.product.GetProductForCartResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:marketplace.product.GetProductForCartResponse)
        marketplace.product.Product.GetProductForCartResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return marketplace.product.Product.internal_static_marketplace_product_GetProductForCartResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return marketplace.product.Product.internal_static_marketplace_product_GetProductForCartResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                marketplace.product.Product.GetProductForCartResponse.class, marketplace.product.Product.GetProductForCartResponse.Builder.class);
      }

      // Construct using marketplace.product.Product.GetProductForCartResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        productId_ = 0L;
        price_ = "";
        available_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return marketplace.product.Product.internal_static_marketplace_product_GetProductForCartResponse_descriptor;
      }

      @java.lang.Override
      public marketplace.product.Product.GetProductForCartResponse getDefaultInstanceForType() {
        return marketplace.product.Product.GetProductForCartResponse.getDefaultInstance();
      }

      @java.lang.Override
      public marketplace.product.Product.GetProductForCartResponse build() {
        marketplace.product.Product.GetProductForCartResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public marketplace.product.Product.GetProductForCartResponse buildPartial() {
        marketplace.product.Product.GetProductForCartResponse result = new marketplace.product.Product.GetProductForCartResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(marketplace.product.Product.GetProductForCartResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.productId_ = productId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.price_ = price_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.available_ = available_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof marketplace.product.Product.GetProductForCartResponse) {
          return mergeFrom((marketplace.product.Product.GetProductForCartResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(marketplace.product.Product.GetProductForCartResponse other) {
        if (other == marketplace.product.Product.GetProductForCartResponse.getDefaultInstance()) return this;
        if (other.getProductId() != 0L) {
          setProductId(other.getProductId());
        }
        if (!other.getPrice().isEmpty()) {
          price_ = other.price_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getAvailable() != false) {
          setAvailable(other.getAvailable());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                productId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                price_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                available_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long productId_ ;
      /**
       * <code>int64 product_id = 1;</code>
       * @return The productId.
       */
      @java.lang.Override
      public long getProductId() {
        return productId_;
      }
      /**
       * <code>int64 product_id = 1;</code>
       * @param value The productId to set.
       * @return This builder for chaining.
       */
      public Builder setProductId(long value) {

        productId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 product_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        productId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object price_ = "";
      /**
       * <code>string price = 2;</code>
       * @return The price.
       */
      public java.lang.String getPrice() {
        java.lang.Object ref = price_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          price_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string price = 2;</code>
       * @return The bytes for price.
       */
      public com.google.protobuf.ByteString
          getPriceBytes() {
        java.lang.Object ref = price_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          price_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string price = 2;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        price_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string price = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        price_ = getDefaultInstance().getPrice();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string price = 2;</code>
       * @param value The bytes for price to set.
       * @return This builder for chaining.
       */
      public Builder setPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        price_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private boolean available_ ;
      /**
       * <code>bool available = 3;</code>
       * @return The available.
       */
      @java.lang.Override
      public boolean getAvailable() {
        return available_;
      }
      /**
       * <code>bool available = 3;</code>
       * @param value The available to set.
       * @return This builder for chaining.
       */
      public Builder setAvailable(boolean value) {

        available_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool available = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvailable() {
        bitField0_ = (bitField0_ & ~0x00000004);
        available_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:marketplace.product.GetProductForCartResponse)
    }

    // @@protoc_insertion_point(class_scope:marketplace.product.GetProductForCartResponse)
    private static final marketplace.product.Product.GetProductForCartResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new marketplace.product.Product.GetProductForCartResponse();
    }

    public static marketplace.product.Product.GetProductForCartResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetProductForCartResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetProductForCartResponse>() {
      @java.lang.Override
      public GetProductForCartResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetProductForCartResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetProductForCartResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public marketplace.product.Product.GetProductForCartResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marketplace_product_GetProductForCartRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marketplace_product_GetProductForCartRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_marketplace_product_GetProductForCartResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_marketplace_product_GetProductForCartResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\022\023marketplace.product\".\n\030" +
      "GetProductForCartRequest\022\022\n\nproduct_id\030\001" +
      " \001(\003\"Q\n\031GetProductForCartResponse\022\022\n\npro" +
      "duct_id\030\001 \001(\003\022\r\n\005price\030\002 \001(\t\022\021\n\tavailabl" +
      "e\030\003 \001(\0102\204\001\n\016ProductService\022r\n\021GetProduct" +
      "ForCart\022-.marketplace.product.GetProduct" +
      "ForCartRequest\032..marketplace.product.Get" +
      "ProductForCartResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_marketplace_product_GetProductForCartRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_marketplace_product_GetProductForCartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marketplace_product_GetProductForCartRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_marketplace_product_GetProductForCartResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_marketplace_product_GetProductForCartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_marketplace_product_GetProductForCartResponse_descriptor,
        new java.lang.String[] { "ProductId", "Price", "Available", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
